# Uncomment the next line to define a global platform for your project
platform :ios, '7.0'

target 'CollectionViewWheelLayoutDemo' do
  pod 'CPCollectionViewWheelLayout', :path => '../'

  target 'CollectionViewWheelLayoutDemoTests' do
    inherit! :search_paths
  end
end
